"""Tests for `skein_glm.preprocessing` — polychoric / polyserial /
mixed correlation matrices for ordinal data.

Coverage:
- Recovery on synthetic ordinal data generated from a known continuous
  Gaussian: discretize via threshold sets, recover the true ρ to
  ≤ 0.05 absolute error at n=2000.
- Polyserial: same recovery test for ordinal × continuous.
- Mixed pipeline auto-detects column type and produces a valid
  correlation matrix.
- Edge cases: degenerate column (single observed level), tiny pair
  sample size, NaN / pairwise deletion.
- Properties: diagonal exactly 1, off-diagonal symmetric, bounded
  in [-1, 1].
- R-anchor: skipped if `tests/fixtures/psych_polychoric.json` is
  absent (the fixture is generated by `tests/fixtures/generate.R`
  via `psych::polychoric` and committed when available).
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

skein = pytest.importorskip("skein_glm")

from skein_glm.preprocessing import (  # noqa: E402
    polychoric_correlation,
    polychoric_covariance_matrix,
    polyserial_correlation,
)


def _correlation_from_pd_matrix(p: int, rho_values: np.ndarray, seed: int) -> np.ndarray:
    """Build a random positive-definite p×p correlation matrix."""
    rng = np.random.default_rng(seed)
    A = rng.standard_normal((p, p))
    R = A @ A.T
    d = np.sqrt(np.diag(R))
    R = R / np.outer(d, d)
    return R


def _draw_latent_gaussian(R: np.ndarray, n: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return rng.multivariate_normal(np.zeros(R.shape[0]), R, size=n)


def _discretize(z: np.ndarray, thresholds: np.ndarray) -> np.ndarray:
    """Bucket continuous z into integer levels via thresholds."""
    return np.digitize(z, thresholds)


# -------------------------------------------------------------------
# polychoric: recovery
# -------------------------------------------------------------------


def test_polychoric_recovers_known_rho_on_5_level_likert():
    """Olsson two-step ML should recover the latent Gaussian
    correlation to within 0.05 at n=2000 with 5-level Likert."""
    rng = np.random.default_rng(0)
    p = 4
    true_R = np.array([
        [1.0, 0.6, 0.3, 0.0],
        [0.6, 1.0, 0.4, 0.2],
        [0.3, 0.4, 1.0, 0.5],
        [0.0, 0.2, 0.5, 1.0],
    ])
    L = np.linalg.cholesky(true_R)
    Z = rng.standard_normal((2000, p)) @ L.T
    thresholds = np.array([-1.0, -0.3, 0.3, 1.0])
    X = _discretize(Z, thresholds)
    R = polychoric_correlation(X)
    np.testing.assert_array_equal(np.diag(R), np.ones(p))
    assert np.max(np.abs(R - R.T)) < 1e-10  # symmetric
    assert np.max(np.abs(R - true_R)) < 0.05


def test_polychoric_recovers_strong_correlation_at_binary():
    """2-level (binary) case reduces to tetrachoric; should still
    recover a strong planted correlation."""
    rng = np.random.default_rng(1)
    n = 5000
    z = rng.multivariate_normal([0, 0], [[1, 0.7], [0.7, 1]], size=n)
    X = (z > 0).astype(int)  # binary
    R = polychoric_correlation(X)
    assert abs(R[0, 1] - 0.7) < 0.05


def test_polychoric_zero_correlation():
    rng = np.random.default_rng(2)
    n = 3000
    z = rng.standard_normal((n, 2))  # uncorrelated
    X = _discretize(z, np.array([-0.5, 0.5]))
    R = polychoric_correlation(X)
    assert abs(R[0, 1]) < 0.05


# -------------------------------------------------------------------
# polyserial: recovery
# -------------------------------------------------------------------


def test_polyserial_recovers_rho_scalar():
    """One ordinal × one continuous: should recover ρ to within 0.05
    at n=2000."""
    rng = np.random.default_rng(3)
    n = 2000
    rho = 0.5
    z = rng.multivariate_normal([0, 0], [[1, rho], [rho, 1]], size=n)
    x_ord = _discretize(z[:, 0], np.array([-1.0, 0.0, 1.0]))
    y_cont = z[:, 1]
    r = polyserial_correlation(x_ord, y_cont)
    assert isinstance(r, float)
    assert abs(r - rho) < 0.05


def test_polyserial_vectorized_shape():
    rng = np.random.default_rng(4)
    n, p_ord, p_cont = 1500, 3, 2
    z = rng.standard_normal((n, p_ord + p_cont))
    x_ord = _discretize(z[:, :p_ord], np.array([-0.5, 0.5]))
    y_cont = z[:, p_ord:]
    R = polyserial_correlation(x_ord, y_cont)
    assert R.shape == (p_ord, p_cont)
    # All uncorrelated columns → all close to 0.
    assert np.max(np.abs(R)) < 0.1


# -------------------------------------------------------------------
# mixed pipeline
# -------------------------------------------------------------------


def test_polychoric_covariance_matrix_auto_dispatches():
    """Mixed pipeline auto-detects continuous (>10 unique values) vs
    ordinal columns and produces a recovered correlation within 0.05
    of the latent truth."""
    rng = np.random.default_rng(5)
    p = 4
    true_R = np.array([
        [1.0, 0.6, 0.3, 0.0],
        [0.6, 1.0, 0.4, 0.2],
        [0.3, 0.4, 1.0, 0.5],
        [0.0, 0.2, 0.5, 1.0],
    ])
    L = np.linalg.cholesky(true_R)
    Z = rng.standard_normal((2000, p)) @ L.T
    # Discretize cols 0, 1 to 5-level; leave cols 2, 3 continuous.
    thresholds = np.array([-1.0, -0.3, 0.3, 1.0])
    X = Z.copy()
    X[:, 0] = _discretize(Z[:, 0], thresholds)
    X[:, 1] = _discretize(Z[:, 1], thresholds)
    R = polychoric_covariance_matrix(X)
    np.testing.assert_array_equal(np.diag(R), np.ones(p))
    assert np.max(np.abs(R - R.T)) < 1e-10
    assert np.max(np.abs(R - true_R)) < 0.05


def test_polychoric_covariance_matrix_explicit_mask():
    """Explicit continuous_mask overrides auto-detection."""
    rng = np.random.default_rng(6)
    n, p = 500, 3
    X = rng.standard_normal((n, p))
    # Force middle column to be treated as ordinal even though it's
    # continuous → its polychoric correlation should still be close to
    # the Pearson value (Olsson works on the marginal CDF, which is
    # well-defined for any distribution).
    R = polychoric_covariance_matrix(
        X, continuous_mask=[True, False, True]
    )
    assert R.shape == (p, p)
    np.testing.assert_array_equal(np.diag(R), np.ones(p))


def test_polychoric_covariance_matrix_feeds_graphical_lasso():
    """End-to-end smoke test: mixed correlation matrix → GraphicalLasso.

    Demonstrates the headline pipeline for psychometrics. We don't
    assert on the precision matrix content here (that's covered by
    the network-recovery tests in test_graph_stability.py); we just
    confirm the API plumbing accepts the polychoric output."""
    rng = np.random.default_rng(7)
    n = 800
    rho = 0.6
    z = rng.multivariate_normal([0, 0, 0], [[1, rho, 0], [rho, 1, 0.3], [0, 0.3, 1]], size=n)
    X = z.copy()
    X[:, 0] = _discretize(z[:, 0], np.array([-0.5, 0.5]))
    X[:, 1] = _discretize(z[:, 1], np.array([-0.5, 0.5]))
    R = polychoric_covariance_matrix(X)
    gl = skein.GraphicalLasso(alpha=0.1).fit(R)
    assert gl.precision_.shape == (3, 3)
    assert np.all(np.isfinite(gl.precision_))


# -------------------------------------------------------------------
# properties / edge cases
# -------------------------------------------------------------------


def test_polychoric_diag_is_one_and_symmetric():
    rng = np.random.default_rng(8)
    X = _discretize(rng.standard_normal((400, 5)), np.array([-0.5, 0.5]))
    R = polychoric_correlation(X)
    np.testing.assert_array_equal(np.diag(R), np.ones(5))
    np.testing.assert_allclose(R, R.T, atol=1e-12)
    assert R.min() >= -1.0 and R.max() <= 1.0


def test_polychoric_pairwise_deletion_with_nan():
    rng = np.random.default_rng(9)
    n = 1000
    rho = 0.5
    z = rng.multivariate_normal([0, 0], [[1, rho], [rho, 1]], size=n)
    X = _discretize(z, np.array([-0.5, 0.5])).astype(float)
    # Punch holes in column 0.
    X[::10, 0] = np.nan
    R = polychoric_correlation(X, missing="pairwise")
    assert np.isfinite(R[0, 1])
    assert abs(R[0, 1] - rho) < 0.1  # looser; we dropped 10% of rows


def test_polychoric_listwise_deletion():
    rng = np.random.default_rng(10)
    n = 1500
    z = rng.multivariate_normal([0, 0], [[1, 0.5], [0.5, 1]], size=n)
    X = _discretize(z, np.array([-0.5, 0.5])).astype(float)
    X[::20, 0] = np.nan
    R_listwise = polychoric_correlation(X, missing="listwise")
    assert np.isfinite(R_listwise[0, 1])


def test_polychoric_rejects_invalid_shape():
    with pytest.raises(ValueError, match="2D"):
        polychoric_correlation(np.array([1, 2, 3]))
    with pytest.raises(ValueError, match="at least 2 columns"):
        polychoric_correlation(np.array([[1], [2], [3]]))


def test_polychoric_rejects_invalid_missing():
    X = np.array([[0, 1], [1, 0], [0, 1]])
    with pytest.raises(ValueError, match="missing"):
        polychoric_correlation(X, missing="invalid")  # type: ignore[arg-type]


def test_polyserial_n_mismatch_raises():
    with pytest.raises(ValueError, match="same n"):
        polyserial_correlation(np.array([0, 1, 0, 1]), np.array([0.1, 0.2]))


def test_polychoric_covariance_matrix_validates_mask_shape():
    X = np.zeros((10, 3))
    with pytest.raises(ValueError, match="continuous_mask"):
        polychoric_covariance_matrix(X, continuous_mask=[True, False])


def test_threshold_endpoints_produce_finite_rectangle_probabilities():
    """Regression: scipy 1.15 (Python 3.10 pip default) returns NaN from
    `multivariate_normal.cdf` when any coordinate is `-np.inf`; this
    silently breaks `_bivariate_rect_prob` (NaN → clipped to _PI_FLOOR →
    constant log-likelihood → Brent returns ±0.236 = golden-section
    init point regardless of true ρ). The fix replaces ±inf endpoints
    with ±_INF_SENTINEL (= 8.0) inside `_thresholds_from_counts`.

    This test exercises the exact failure mode: build a threshold
    vector with the new sentinel endpoints, compute the bivariate
    rectangle probabilities at several ρ values, and assert finiteness
    of *every* cell. If scipy regresses on inf-handling again, or if
    someone reintroduces a raw ±inf into the threshold sentinel, this
    will fail under any scipy version that mishandles inf in the CDF
    input.
    """
    from skein_glm.preprocessing import _bivariate_rect_prob, _thresholds_from_counts

    # 5-level Likert marginal — exercises the same endpoint structure
    # as the failing tests reproduced.
    counts = np.array([100, 200, 400, 200, 100], dtype=np.int64)
    tau = _thresholds_from_counts(counts)
    assert np.all(np.isfinite(tau)), f"threshold sentinels must be finite, got {tau}"
    for rho in (-0.7, -0.236, 0.0, 0.236, 0.7):
        pi = _bivariate_rect_prob(tau, tau, rho)
        assert np.all(np.isfinite(pi)), (
            f"rectangle probability has NaN/inf at rho={rho}; scipy "
            f"`multivariate_normal.cdf` may be regressing on inf-handling"
        )
        # Cell probabilities should sum to ~1 (probability mass over
        # the full real plane).
        assert abs(pi.sum() - 1.0) < 1e-6, f"pi sums to {pi.sum()} at rho={rho}"


# -------------------------------------------------------------------
# R-anchor (skipped without fixture)
# -------------------------------------------------------------------


_FIXTURE = Path(__file__).parent / "fixtures" / "psych_polychoric.json"


def test_polychoric_matches_r_psych():
    """Agreement with R `psych::polychoric` to ≤ 5e-3 elementwise on a
    fixed-seed problem. Skipped if the fixture is absent — fixture is
    generated by `Rscript tests/fixtures/generate.R` (when R + psych
    are available) and committed to the repo."""
    if not _FIXTURE.is_file():
        pytest.skip(
            f"fixture {_FIXTURE.name} missing; run `Rscript tests/fixtures/"
            "generate.R` to generate (requires R + psych package)"
        )
    with open(_FIXTURE) as f:
        fix = json.load(f)
    X = np.asarray(fix["X"], dtype=np.int64)
    R_r = np.asarray(fix["R"], dtype=np.float64)
    R = polychoric_correlation(X)
    np.testing.assert_allclose(R, R_r, atol=5e-3)
