"""Regression tests against R reference fits.

Each fixture in tests/fixtures/ was generated by tests/fixtures/generate.R
running glmnet / ncvreg / grpreg on a small synthetic problem with a
fixed seed and tight convergence (eps=1e-10). These tests load each
fixture and assert that skein's fit on the same X / y / λ-grid agrees
with the R reference along three dimensions:

1. **Active set match**: which coefficients are non-zero (>1e-6 in
   magnitude). The regularization path's selection behavior is the
   most important thing to track — if skein silently changes which
   features get selected, this test catches it.

2. **Sign agreement on active features**: for any feature non-zero
   in the reference fit, skein's coef must have the same sign.

3. **Magnitude agreement at the smallest λ**: at the least-
   regularized end of the path, both solvers approach the same
   unregularized optimum, so coefficients should agree to ~1e-3.
   Mid-path agreement is looser because different inner stopping
   criteria (glmnet's relative-improvement, ncvreg's β-change,
   skein's KKT-based) leave the solvers at slightly different points
   in the convergence basin.

If a fixture is missing the test is skipped (lets developers run
pytest without R installed). To regenerate, install R + glmnet +
ncvreg + grpreg + jsonlite + survival, then run:

    Rscript tests/fixtures/generate.R
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
import pytest

skein = pytest.importorskip("skein_glm")

FIXTURES_DIR = Path(__file__).parent / "fixtures"
ACTIVE_EPS = 1e-6

# Set SKEIN_REQUIRE_FIXTURES=1 in CI so missing fixtures fail loudly
# instead of silently skipping. Local devs without R installed see the
# original soft-skip behavior. Fixtures are checked into git, so the
# only way they go missing in CI is a deletion that should be caught.
_REQUIRE_FIXTURES = os.environ.get("SKEIN_REQUIRE_FIXTURES") == "1"


def _load_fixture(name: str) -> dict | None:
    path = FIXTURES_DIR / f"{name}.json"
    if not path.is_file():
        return None
    with open(path) as f:
        data = json.load(f)
    for key in ("X", "coefs"):
        if key in data:
            data[key] = np.asarray(data[key], dtype=np.float64)
    for key in ("y", "lambdas", "intercepts", "beta_true",
                "groups", "group_multiplier", "time", "event"):
        if key in data:
            data[key] = np.asarray(data[key])
    return data


def _skipped_if_missing(name: str) -> dict:
    fix = _load_fixture(name)
    if fix is None:
        msg = (
            f"fixture {name}.json missing; run "
            "`Rscript tests/fixtures/generate.R` to generate"
        )
        if _REQUIRE_FIXTURES:
            pytest.fail(msg)
        pytest.skip(msg)
    return fix


def _assert_path_matches(
    skein_coefs: np.ndarray,
    ref_coefs: np.ndarray,
    *,
    smallest_lambda_atol: float,
    label: str,
    active_set_fuzz_frac: float = 0.10,
    sign_check_threshold: float = 1e-3,
) -> None:
    """Check three regression invariants between coefficient paths of
    shape ``(n_lambdas, p)``.

    Parameters
    ----------
    smallest_lambda_atol : float
        Absolute tolerance for the magnitude check at the least-
        regularized λ — where both solvers approach the same
        unregularized optimum so agreement should be tight.
    active_set_fuzz_frac : float, default 0.10
        Fraction of features (rounded up to ≥ 2) allowed to disagree
        on inclusion-vs-exclusion at any single λ. The active-set
        boundary is fuzzy at moderate λ because different inner
        stopping criteria (KKT in skein, β-change in ncvreg, relative-
        improvement in glmnet) leave the solvers at slightly different
        points; nonconvex penalties add another layer (LLA can find
        different local minima depending on initialization). Loosen
        this for nonconvex GLMs (logistic MCP, group MCP) where the
        fuzz is genuinely larger.
    """
    assert skein_coefs.shape == ref_coefs.shape, (
        f"{label}: shape mismatch {skein_coefs.shape} vs {ref_coefs.shape}"
    )

    skein_active = np.abs(skein_coefs) > ACTIVE_EPS
    ref_active = np.abs(ref_coefs) > ACTIVE_EPS
    disagree_per_lambda = (skein_active != ref_active).sum(axis=1)
    p = ref_coefs.shape[1]
    fuzz_thresh = max(2, int(np.ceil(active_set_fuzz_frac * p)))
    assert (disagree_per_lambda <= fuzz_thresh).all(), (
        f"{label}: active-set disagreement exceeds {fuzz_thresh} features at "
        f"some λ (max {disagree_per_lambda.max()} / {p}). "
        f"Per-λ counts: {disagree_per_lambda.tolist()}"
    )

    # Sign check restricted to "meaningfully active" features —
    # |β| > sign_check_threshold in BOTH solvers. Below that the sign
    # is essentially noise (both solvers are at near-zero values right
    # at the active-set boundary; any sign on a tiny coefficient is
    # arbitrary). Default 1e-3 works for convex paths; loosen for
    # nonconvex (LLA can flip signs of small early-path coefficients
    # depending on which local minimum each solver settles on).
    meaningful = (np.abs(skein_coefs) > sign_check_threshold) & (
        np.abs(ref_coefs) > sign_check_threshold
    )
    sign_match = np.sign(skein_coefs[meaningful]) == np.sign(ref_coefs[meaningful])
    assert sign_match.all(), (
        f"{label}: sign mismatch on meaningfully-active features "
        f"({(~sign_match).sum()} disagreements out of {meaningful.sum()})"
    )

    np.testing.assert_allclose(
        skein_coefs[-1], ref_coefs[-1],
        atol=smallest_lambda_atol,
        err_msg=f"{label}: smallest-λ coefs disagree beyond {smallest_lambda_atol}",
    )


# ---- glmnet lasso (gaussian) ---------------------------------------------


def test_glmnet_lasso_gaussian_matches_skein_mcp_high_gamma():
    fix = _skipped_if_missing("glmnet_lasso_gaussian")
    model = skein.MCPPathRegressor(
        gamma=1e6,
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=20000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=5e-3,
        label="glmnet lasso gaussian vs skein MCP γ=1e6",
    )


# ---- ncvreg MCP (gaussian) -----------------------------------------------


def test_ncvreg_mcp_gaussian_matches_skein():
    fix = _skipped_if_missing("ncvreg_mcp_gaussian")
    model = skein.MCPPathRegressor(
        gamma=fix["gamma"],
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-3,
        label="ncvreg MCP gaussian vs skein",
    )


# ---- ncvreg SCAD (gaussian) ----------------------------------------------


def test_ncvreg_scad_gaussian_matches_skein():
    fix = _skipped_if_missing("ncvreg_scad_gaussian")
    model = skein.SCADPathRegressor(
        a=fix["a"],
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-3,
        label="ncvreg SCAD gaussian vs skein",
    )


# ---- grpreg group lasso (gaussian) ---------------------------------------


def test_grpreg_grlasso_gaussian_matches_skein():
    fix = _skipped_if_missing("grpreg_grlasso_gaussian")
    groups = fix["groups"].astype(np.int64) - 1   # R 1-indexed → 0-indexed
    model = skein.GroupLassoPathRegressor(
        groups=groups,
        weights=fix["group_multiplier"].astype(np.float64),
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-3,
        label="grpreg grLasso vs skein",
    )


# ---- grpreg group MCP (gaussian) -----------------------------------------


def test_grpreg_grmcp_gaussian_matches_skein():
    fix = _skipped_if_missing("grpreg_grmcp_gaussian")
    groups = fix["groups"].astype(np.int64) - 1
    model = skein.GroupMCPPathRegressor(
        groups=groups,
        weights=fix["group_multiplier"].astype(np.float64),
        gamma=fix["gamma"],
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        max_outer=50,
        outer_tol=1e-10,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-3,
        # Group MCP nonconvex: LLA can find different local minima
        # depending on initialization, so the active-set boundary is
        # fuzzier than for convex group lasso.
        active_set_fuzz_frac=0.40,
        # Early-path coefs at |β|~0.01 can sign-flip between LLA
        # local minima; only check signs once both solvers settle
        # on coefficients that are clearly active.
        sign_check_threshold=5e-2,
        label="grpreg grMCP vs skein",
    )


# ---- glmnet binomial lasso -----------------------------------------------


def test_glmnet_lasso_binomial_matches_skein_mcp_high_gamma():
    fix = _skipped_if_missing("glmnet_lasso_binomial")
    model = skein.LogisticMCPPathRegressor(
        gamma=1e6,
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=20000,
        max_outer=50,
        outer_tol=1e-10,
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-2,
        label="glmnet binomial lasso vs skein logistic MCP γ=1e6",
    )


# ---- ncvreg binomial MCP -------------------------------------------------


def test_ncvreg_mcp_binomial_matches_skein():
    fix = _skipped_if_missing("ncvreg_mcp_binomial")
    model = skein.LogisticMCPPathRegressor(
        gamma=fix["gamma"],
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        max_outer=50,
        outer_tol=1e-10,
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-2,
        # Nonconvex logistic via prox-Newton (skein) vs IRLS (ncvreg)
        # — both converge to a stationary point, but mid-path active
        # sets differ measurably.
        active_set_fuzz_frac=0.40,
        label="ncvreg binomial MCP vs skein logistic MCP",
    )


# ---- glmnet Cox lasso ----------------------------------------------------


def test_glmnet_lasso_cox_matches_skein_mcp_high_gamma():
    fix = _skipped_if_missing("glmnet_lasso_cox")
    model = skein.CoxMCPPathRegressor(
        gamma=1e6,
        lambdas=fix["lambdas"],
        standardize=True,
        tol=1e-10,
        max_iter=20000,
        max_outer=50,
        outer_tol=1e-10,
    ).fit(fix["X"], fix["time"].astype(np.float64), fix["event"].astype(np.float64))
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=2e-2,
        label="glmnet Cox lasso vs skein Cox MCP γ=1e6",
    )


# ---- M14c.3 at-scale (n=500, p=100) fixtures -----------------------------
#
# These exercise the same penalty / family combinations as the small tier
# above but at a size that produces multiple outer iters per λ and a
# meaningfully sparse active set (top-8 features active in p=100). The
# tolerances are looser because LLA local-min divergence on nonconvex
# problems widens with p, and the active-set boundary fuzz grows with the
# number of features. A regression that *only* fires at scale (e.g.
# screening rule applied to the wrong λ index, fixed-cost outer overhead
# that scales super-linearly) gets caught here when the small tier would
# miss it.
#
# Skipped cleanly when fixtures absent — same `SKEIN_REQUIRE_FIXTURES=1`
# gate as the small tier.


def test_glmnet_lasso_gaussian_mid_matches_skein_mcp_high_gamma():
    fix = _skipped_if_missing("glmnet_lasso_gaussian_mid")
    model = skein.MCPPathRegressor(
        gamma=1e6,
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=20000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=1e-2,
        active_set_fuzz_frac=0.15,
        label="glmnet lasso gaussian (mid) vs skein MCP γ=1e6",
    )


def test_ncvreg_mcp_gaussian_mid_matches_skein():
    fix = _skipped_if_missing("ncvreg_mcp_gaussian_mid")
    model = skein.MCPPathRegressor(
        gamma=fix["gamma"],
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-10,
        max_iter=50000,
        screening="off",
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=5e-3,
        active_set_fuzz_frac=0.15,
        label="ncvreg MCP gaussian (mid) vs skein",
    )


def test_glmnet_lasso_binomial_mid_matches_skein_mcp_high_gamma():
    fix = _skipped_if_missing("glmnet_lasso_binomial_mid")
    model = skein.LogisticMCPPathRegressor(
        gamma=1e6,
        lambdas=fix["lambdas"],
        standardize=True,
        fit_intercept=True,
        tol=1e-8,
        max_iter=20000,
    ).fit(fix["X"], fix["y"])
    _assert_path_matches(
        model.coefs_, fix["coefs"],
        smallest_lambda_atol=5e-2,
        active_set_fuzz_frac=0.15,
        label="glmnet binomial lasso (mid) vs skein logistic MCP γ=1e6",
    )


# ---- meta tests ----------------------------------------------------------


def test_fixtures_directory_exists():
    assert FIXTURES_DIR.is_dir(), f"expected {FIXTURES_DIR} to exist"


def test_at_least_one_fixture_present():
    fixtures = sorted(FIXTURES_DIR.glob("*.json"))
    if not fixtures:
        msg = (
            "no fixtures found; run `Rscript tests/fixtures/generate.R` "
            "to generate (requires R + glmnet + ncvreg + grpreg + "
            "jsonlite + survival)"
        )
        if _REQUIRE_FIXTURES:
            pytest.fail(msg)
        pytest.skip(msg)
    assert len(fixtures) >= 1
