"""Type stubs for the Rust extension module."""
from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

def solve_mcp_ls(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    lambda_: float,
    gamma: float,
    *,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
) -> tuple[NDArray[np.float64], dict]: ...
def solve_scad_ls(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    lambda_: float,
    a: float,
    *,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
) -> tuple[NDArray[np.float64], dict]: ...
def solve_mcp_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],  # coefs (n_lambdas, p)
    NDArray[np.float64],  # intercepts (n_lambdas,)
    NDArray[np.float64],  # lambdas (n_lambdas,)
    dict,                 # info
]: ...
def solve_scad_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_group_lasso_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_sparse_group_lasso_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_group_mcp_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_sparse_group_mcp_ls_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_scad_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_group_lasso_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_group_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_sparse_group_lasso_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_sparse_group_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_scad_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_group_lasso_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_group_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_sparse_group_lasso_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_poisson_sparse_group_mcp_path(
    x: NDArray[np.float64],
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_mcp_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_scad_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_group_lasso_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_group_mcp_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_sparse_group_lasso_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_mcp_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_group_lasso_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_group_mcp_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_sparse_group_lasso_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_sparse_group_mcp_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    parallel: bool = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_scad_ls_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_cox_sparse_group_mcp_path(
    x: NDArray[np.float64],
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64],
    NDArray[np.float64],
    NDArray[np.float64],
    dict,
]: ...
def solve_logistic_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_scad_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_sparse_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_sparse_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_scad_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_sparse_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_poisson_sparse_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_scad_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    *,
    a: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_sparse_group_lasso_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_cox_sparse_group_mcp_path_sparse(
    x_data: NDArray[np.float64],
    x_indices: NDArray[np.int64],
    x_indptr: NDArray[np.int64],
    n_rows: int,
    n_cols: int,
    time: NDArray[np.float64],
    event: NDArray[np.float64],
    groups: NDArray[np.int64],
    *,
    gamma: float = ...,
    alpha: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    coord_weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_mcp_ls_path_mmap(
    path: str,
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    screening: str = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
def solve_logistic_mcp_path_mmap(
    path: str,
    n_rows: int,
    n_cols: int,
    y: NDArray[np.float64],
    *,
    gamma: float = ...,
    lambdas: NDArray[np.float64] | None = ...,
    n_lambdas: int = ...,
    lambda_min_ratio: float = ...,
    weights: NDArray[np.float64] | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    acceleration: int | None = ...,
    fit_intercept: bool = ...,
    standardize_x: bool = ...,
    max_outer: int = ...,
    outer_tol: float = ...,
) -> tuple[
    NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], dict,
]: ...
