"""Table builders — render LaTeX (booktabs) plus a Markdown mirror.

Convention: every `.tex` writes a sibling `.md` next to it for the
docs pipeline. The LaTeX uses `\\toprule`, `\\midrule`, `\\bottomrule`
from booktabs, and `siunitx` is *not* required.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def _to_md(df: pd.DataFrame) -> str:
    """Pandas-only Markdown rendering (avoids the optional `tabulate` dep)."""
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |"]
    lines.append("| " + " | ".join("---" for _ in cols) + " |")
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(str(row[c]) for c in cols) + " |")
    return "\n".join(lines) + "\n"


_DATAFIT_PREFIX = [
    ("Multinomial", "Multinomial"),     # check before "Logistic"-substring matches
    ("Logistic", "Logistic"),
    ("Poisson", "Poisson"),
    ("Cox", "Cox"),
    ("Huber", "Huber"),
    ("MultiTask", "MultiTask"),
    ("Graphical", "Graphical"),
    ("JointGraphical", "JointGraphical"),
]
_PENALTY_KEYWORD = [
    ("SparseGroupMCP", "sgMCP"),
    ("SparseGroupSCAD", "sgSCAD"),
    ("SparseGroupLasso", "sgLasso"),
    ("SparseGroupElasticNet", "sgEN"),
    ("GroupMCP", "grMCP"),
    ("GroupSCAD", "grSCAD"),
    ("GroupLasso", "grLasso"),
    ("GroupElasticNet", "grEN"),
    ("ElasticNet", "EN"),
    ("MCP", "MCP"),
    ("SCAD", "SCAD"),
    ("Lasso", "Lasso"),
    ("Bridge", "Bridge"),
]


_GRAPHICAL_LEAVES = {
    "GraphicalLasso": ("Graphical", "Lasso"),
    "GraphicalMCP":   ("Graphical", "MCP"),
    "GraphicalSCAD":  ("Graphical", "SCAD"),
    "JointGraphicalLasso": ("JointGraphical", "Lasso"),
    "JointGraphicalMCP":   ("JointGraphical", "MCP"),
}


def _classify_estimator(class_name: str) -> tuple[str, str] | None:
    """Map an estimator class name (e.g. 'LogisticGroupMCPPathRegressor')
    to (datafit, penalty) or None if it's not a (datafit × penalty) leaf."""
    if class_name.startswith("_"):
        return None
    # Graphical / JointGraphical classes don't follow the Regressor naming.
    if class_name in _GRAPHICAL_LEAVES:
        return _GRAPHICAL_LEAVES[class_name]
    if not class_name.endswith(("PathRegressor", "Regressor", "PathCV")):
        return None
    body = (class_name.removesuffix("PathRegressor")
                    .removesuffix("Regressor")
                    .removesuffix("PathCV"))
    # Strip the datafit prefix.
    datafit = "Gaussian"
    rest = body
    for prefix, label in _DATAFIT_PREFIX:
        if body.startswith(prefix):
            datafit = label
            rest = body[len(prefix):]
            break
    # Then match the penalty by keyword.
    for kw, pen in _PENALTY_KEYWORD:
        if rest == kw or rest.startswith(kw):
            return (datafit, pen)
    return None


def _enumerate_skein_estimators() -> dict[tuple[str, str], list[str]]:
    """Walk skein_glm.estimators (+ multinomial, multitask, debiased) and
    group public estimator class names by (datafit, penalty)."""
    out: dict[tuple[str, str], list[str]] = {}
    try:
        import skein_glm
    except Exception:
        return out
    seen: set[str] = set()
    for mod_name in ("skein_glm.estimators", "skein_glm.multinomial",
                     "skein_glm.multitask", "skein_glm.debiased"):
        try:
            mod = __import__(mod_name, fromlist=["*"])
        except Exception:
            continue
        for name in dir(mod):
            if name in seen:
                continue
            seen.add(name)
            cls = getattr(mod, name)
            if not isinstance(cls, type):
                continue
            cls_module = getattr(cls, "__module__", "")
            if not cls_module.startswith("skein_glm"):
                continue
            classified = _classify_estimator(name)
            if classified is None:
                continue
            out.setdefault(classified, []).append(name)
    return out


def estimator_surface(out: Path) -> None:
    """T1 — public estimator surface, generated by introspection
    over `skein_glm`. Each (Datafit, Penalty) cell shows the count of
    public estimator classes (single-λ + path + CV may all share a
    cell) and whether at least one external comparator exists in
    runners.registry."""
    from benches.v2.runners.registry import LADDER

    by_cell = _enumerate_skein_estimators()
    # Normalize (Datafit, Penalty) labels for the comparator-lookup keys
    # (registry uses lowercase keys like ("logistic", "mcp")).
    datafit_lookup = {
        "Gaussian": "gaussian", "Logistic": "logistic", "Poisson": "poisson",
        "Cox": "cox", "Multinomial": "multinomial", "Huber": "huber",
        "MultiTask": "multitask", "Graphical": "gaussian_inv_cov",
        "JointGraphical": "joint_inv_cov",
    }
    penalty_lookup = {
        "Lasso": "lasso", "MCP": "mcp", "SCAD": "scad", "EN": "elastic_net",
        "grLasso": "group_lasso", "grMCP": "group_mcp", "grSCAD": "group_scad",
        "grEN": "group_elastic_net",
        "sgLasso": "sparse_group_lasso", "sgMCP": "sparse_group_mcp",
        "sgSCAD": "sparse_group_scad", "sgEN": "sparse_group_elastic_net",
        "Bridge": "bridge",
    }

    rows = []
    for (datafit, penalty), classes in sorted(by_cell.items()):
        external = LADDER.get(
            (datafit_lookup.get(datafit, ""), penalty_lookup.get(penalty, "")),
            {},
        )
        rows.append({
            "Datafit": datafit, "Penalty": penalty,
            "n_classes": len(classes),
            "external": bool(external),
            "_classes": classes,
        })

    df = pd.DataFrame(rows)
    pivot_count = df.pivot_table(index="Datafit", columns="Penalty",
                                 values="n_classes", aggfunc="first")
    pivot_ext   = df.pivot_table(index="Datafit", columns="Penalty",
                                 values="external", aggfunc="first")

    def cell_fmt(count, has_ext):
        if pd.isna(count) or count == 0:
            return ""
        mark = "$\\checkmark$" if has_ext is True else "--"
        return f"{int(count)} {mark}"

    cells = pd.DataFrame("", index=pivot_count.index, columns=pivot_count.columns)
    for i in pivot_count.index:
        for j in pivot_count.columns:
            cells.loc[i, j] = cell_fmt(pivot_count.loc[i, j],
                                       pivot_ext.loc[i, j]
                                       if j in pivot_ext.columns else None)
    tex = cells.to_latex(escape=False, column_format="l" + "c" * cells.shape[1])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap_tex(
        "T1: Public estimator surface (skein_glm) and external-comparator coverage",
        "tab:estimator_surface", tex,
        caption=("Count of public estimator classes per (datafit, penalty); "
                 "$\\checkmark$ marks cells with at least one direct external "
                 "comparator (sklearn, glmnet, ncvreg, grpreg, skglm, celer, "
                 "lifelines). -- marks skein-only cells benchmarked against "
                 "synthetic ground truth instead.")))
    out.with_suffix(".md").write_text(_to_md(cells.reset_index()))


def headline_timings(inputs: list[Path], out: Path) -> None:
    """T2 — headline timings per (scenario, package), medium/dense (regime=deep internal key), with IQR."""
    rows = []
    for path in inputs:
        agg = json.loads(path.read_text())
        for cell in agg["cells"]:
            if cell["size"] != "medium" or cell["regime"] != "deep":
                continue
            rows.append({
                "Scenario": agg["scenario"],
                "Package":  cell["package"],
                "n":        cell["n"],
                "p":        cell["p"],
                "Median (s)": round(cell["fit_time_s_median"], 3),
                "Min (s)":    round(cell["fit_time_s_min"], 3),
                "Max (s)":    round(cell["fit_time_s_max"], 3),
                "Active":   int(cell["active_set_size_median"]),
                "Seeds":    cell["n_seeds"],
            })
    if not rows:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("% T2: no headline data available\n")
        out.with_suffix(".md").write_text("_T2: no headline data available_\n")
        return
    df = pd.DataFrame(rows).sort_values(["Scenario", "Package"])
    tex = df.to_latex(index=False, escape=False)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap_tex(
        "T2: Headline timings, medium size, dense regime",
        "tab:headline_timings", tex,
        caption=("Median over 5 seeds with min/max envelope; one warm-up "
                 "call discarded.")))
    out.with_suffix(".md").write_text(_to_md(df))


def recovery(inputs: list[Path], out: Path) -> None:
    """T4 — synthetic recovery summary: support F1, β-RMSE, hat support size
    at AIC/BIC/EBIC-selected λ, per (scenario, package). Medium/dense cells
    (internal regime key = "deep"; the path runs into the saturated tail)."""
    rows = []
    for path in inputs:
        agg = json.loads(path.read_text())
        for cell in agg["cells"]:
            if cell["regime"] != "deep":
                continue
            sm = cell.get("selection_mean") or {}
            if not sm:
                continue
            for crit, vals in sm.items():
                rows.append({
                    "Scenario": agg["scenario"],
                    "Package":  cell["package"],
                    "n":        cell["n"],
                    "Criterion": crit.upper(),
                    "F1":       round(vals["support_f1_mean"], 3),
                    "RMSE":     round(vals["beta_rmse_mean"], 4),
                    "|Ŝ|":     round(vals["hat_support_size_mean"], 1),
                    "Seeds":    vals["n_seeds"],
                })
    if not rows:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("% T4: no recovery data available\n")
        out.with_suffix(".md").write_text("_T4: no recovery data available_\n")
        return
    df = pd.DataFrame(rows).sort_values(["Scenario", "Package", "n", "Criterion"])
    tex = df.to_latex(index=False, escape=False)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap_tex(
        "T4: Recovery at IC-selected $\\lambda$ (dense regime, mean across seeds)",
        "tab:recovery", tex,
        caption=("Support-F1, $\\beta$-RMSE, and selected support size at "
                 "AIC / BIC / EBIC-selected $\\lambda$ along the dense-tail "
                 "path (`lambda_min_ratio = 1e-3`).")))
    out.with_suffix(".md").write_text(_to_md(df))


def realdata(inputs: list[Path], out: Path) -> None:
    """T5 — per-dataset, per-estimator real-data results: CV deviance,
    selected support size, refit time."""
    rows = []
    for path in inputs:
        for line in path.read_text().splitlines():
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("% T5: no real-dataset results available\n")
        out.with_suffix(".md").write_text("_T5: no real-dataset results_\n")
        return
    table = []
    for r in rows:
        if "fold_deviance_at_lambda_min" not in r:
            continue
        fd = r["fold_deviance_at_lambda_min"]
        mean = sum(fd) / len(fd)
        std = (sum((x - mean) ** 2 for x in fd) / max(1, len(fd) - 1)) ** 0.5
        table.append({
            "Dataset":   r["dataset"],
            "Estimator": r["estimator"],
            "n":         r["n"],
            "p":         r["p"],
            "Family":    r["family"],
            "CV dev (mean)": round(mean, 4),
            "CV dev (std)":  round(std, 4),
            "|Ŝ| at λ_min":  r["final_support_size_lambda_min"],
            "CV time (s)":   round(r["cv_seconds"], 2),
            "Source":   "synthetic" if r.get("used_synthetic") else "real",
        })
    df = pd.DataFrame(table).sort_values(["Dataset", "Estimator"])
    tex = df.to_latex(index=False, escape=False)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap_tex(
        "T5: Real-dataset case-study results",
        "tab:realdata", tex,
        caption=("CV deviance (mean $\\pm$ s.d. across folds) at "
                 "$\\lambda_{\\min}$, selected support size, and CV wall-clock.")))
    out.with_suffix(".md").write_text(_to_md(df))


def environment(inputs: list[Path], out: Path) -> None:
    """T6 — environment summary across all cells."""
    rows = []
    for path in inputs:
        rows.append(json.loads(path.read_text()))
    if not rows:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("% T6: no env captures available\n")
        return
    # Collapse: every (host_id, git_rev) pair → one row with versions.
    by_host: dict[str, dict] = {}
    for r in rows:
        h = r["host_id"]
        by_host.setdefault(h, {
            "host_id": h, "cpu": r.get("cpu"), "blas": r.get("blas"),
            "cpu_count": r.get("cpu_count"), "os": r.get("os"),
            "python": r.get("python"), "git_rev": r.get("git_rev"),
            "pip": dict(r.get("pip") or {}),
        })
        by_host[h]["pip"].update(r.get("pip") or {})
    df = pd.DataFrame([
        {
            "host_id": v["host_id"],
            "CPU":     v["cpu"],
            "BLAS":    v["blas"],
            "cores":   v["cpu_count"],
            "OS":      v["os"],
            "Python":  v["python"],
            "git":     (v["git_rev"] or "")[:8],
            "skein":   v["pip"].get("skein-glm", "?"),
            "numpy":   v["pip"].get("numpy", "?"),
            "scipy":   v["pip"].get("scipy", "?"),
            "sklearn": v["pip"].get("scikit-learn", "?"),
            "skglm":   v["pip"].get("skglm", "?"),
            "celer":   v["pip"].get("celer", "?"),
        }
        for v in by_host.values()
    ])
    tex = df.to_latex(index=False, escape=False)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_wrap_tex(
        "T6: Benchmark environment(s)",
        "tab:environment", tex,
        caption=("Host fingerprint, BLAS link, and key package versions. "
                 "host_id is a hash of (CPU, BLAS, cores) — figures refuse "
                 "to mix host_ids.")))
    out.with_suffix(".md").write_text(_to_md(df))


def _wrap_tex(title: str, label: str, body: str, caption: str) -> str:
    return (
        "\\begin{table}[t]\n"
        f"  \\centering\n"
        f"  \\caption{{{caption}}}\n"
        f"  \\label{{{label}}}\n"
        f"{body}"
        "\\end{table}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub_t1 = sub.add_parser("estimator_surface")
    sub_t1.add_argument("--out", type=Path, required=True)

    sub_t2 = sub.add_parser("headline_timings")
    sub_t2.add_argument("--inputs", nargs="+", type=Path, required=True)
    sub_t2.add_argument("--out", type=Path, required=True)

    sub_t4 = sub.add_parser("recovery")
    sub_t4.add_argument("--inputs", nargs="+", type=Path, required=True)
    sub_t4.add_argument("--out", type=Path, required=True)

    sub_t5 = sub.add_parser("realdata")
    sub_t5.add_argument("--inputs", nargs="+", type=Path, required=True)
    sub_t5.add_argument("--out", type=Path, required=True)

    sub_t6 = sub.add_parser("environment")
    sub_t6.add_argument("--inputs", nargs="+", type=Path, required=True)
    sub_t6.add_argument("--out", type=Path, required=True)

    a = ap.parse_args()
    if a.cmd == "estimator_surface":
        estimator_surface(a.out)
    elif a.cmd == "headline_timings":
        headline_timings(a.inputs, a.out)
    elif a.cmd == "recovery":
        recovery(a.inputs, a.out)
    elif a.cmd == "realdata":
        realdata(a.inputs, a.out)
    elif a.cmd == "environment":
        environment(a.inputs, a.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
